-- Run this once in Supabase SQL Editor.
-- It creates the cloud-synced workout history table and locks it to each signed-in user.

create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_date date not null,
  completed_exercises jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, workout_date)
);

alter table public.workout_logs enable row level security;

create policy "Users can read their own workout logs"
on public.workout_logs for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own workout logs"
on public.workout_logs for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own workout logs"
on public.workout_logs for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own workout logs"
on public.workout_logs for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.set_workout_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists workout_logs_updated_at on public.workout_logs;
create trigger workout_logs_updated_at
before update on public.workout_logs
for each row execute function public.set_workout_updated_at();
